sms_raw=SMSSpamCollection
str(sms_raw)
sms_raw$V1=factor(sms_raw$V1)
str(sms_raw$V1)
table(sms_raw$V1)
round(prop.table(table(sms_raw$V1))*100,digits=10)
library(tm)
sms_corpus=Corpus(VectorSource(sms_raw$V2))
inspect(sms_corpus[1:3])
corpus_clean=tm_map(sms_corpus,tolower)
corpus_clean=tm_map(corpus_clean,removeNumbers)
corpus_clean=tm_map(corpus_clean,removeWords,stopwords())
corpus_clean=tm_map(corpus_clean,removePunctuation)
corpus_clean=tm_map(corpus_clean, stripWhitespace)
sms_dtm=DocumentTermMatrix(corpus_clean)
